# Generated by Django 4.2.13 on 2024-05-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('gambar', models.FileField(upload_to='static/')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keterangan', models.TextField(null=True)),
            ],
        ),
    ]
